version: '3.8'

services:
  arangodb:
    image: arangodb/arangodb:latest
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=App@1234  # Or any strong password you choose
    volumes:
      - arangodb_data:/data/db

volumes:
  arangodb_data: